.TH LD 1
.SH NAME
ld \- link editor
.SH SYNOPSIS
.B ld
[ option ] file ...
.SH DESCRIPTION
.I Ld\^
combines several
object programs into one, resolves external
references, and searches libraries.
In the simplest case several object
files are given, and
.I ld\^
combines them, producing
an object module which can be either executed or
become the input for a further
.I ld\^
run.
(In the latter case, the
.B \-r
option must be given
to preserve the relocation bits.)
The output of
.I ld\^
is left on
.BR a.out .
This file is made executable
only if no errors occurred during the load.
.PP
The argument routines are concatenated in the order
specified.  The entry point of the output is the
beginning of the first routine.
.PP
If any argument is a library, it is searched exactly once
at the point it is encountered in the argument list.
Only those routines defining an unresolved external
reference are loaded.
If a routine from a library
references another routine in the library,
the referenced routine must appear after the
referencing routine in the library.
Thus the order of programs within libraries
may be important.
.PP
The symbols "\_etext", "\_edata" and "\_end"
("etext", "edata" and "end" in C)
are reserved, and if referred to,
are set to the first location above the program,
the first location above initialized data,
and the first location above all data respectively.
It is erroneous to define these symbols.
.PP
.I Ld\^
understands several options.
Except for
.BR \-l ,
they should appear before the file names.
.TP "\w'\fB\-LD\fI\ x\fR\ \ 'u" 
.B  \-s
"Strip" the output, that is, remove the symbol table
and relocation bits to save space (but impair the
usefulness of the debugger).
This information can also be removed by
.IR strip\^ (1).
.TP 
.B  \-u
Take the following argument as a symbol and enter
it as undefined in the symbol table.  This is useful
for loading wholly from a library, since initially the symbol
table is empty and an unresolved reference is needed
to force the loading of the first routine.
.TP 
.BI \-l x
This
option is an abbreviation for the library name
"\fB/lib/lib\fIx\fB.a\fR",
where
.I x\^
is a string.
If that does not exist,
.I ld\^
tries
"\fB/usr/lib/lib\fIx\fB.a\fR".
A library is searched when its name is encountered,
so the placement of a
.B  \-l
is significant.
.TP 
.B  \-x
Do not preserve local
(non-.globl) symbols in the output symbol table; only enter
external symbols.
This option saves some space in the output file.
.TP 
.B  \-X
Save local symbols
except for those whose names begin with "L".
This option is used by
.IR cc\^ (1)
to discard internally generated labels while
retaining symbols local to routines.
.TP 
.B  \-r
Generate relocation bits in the output file
so that it can be the subject of another
.I ld\^
run.
This flag also prevents final definitions from being
given to common symbols,
and suppresses the "undefined symbol" diagnostics.
.TP
.BI \-R\  x
Set starting relocation address of program to
.I x\^
.RI ( x\^
is in hex).
.TP
.BI \-LT\  x
Set the text relocation address to
.I x\^
.RI ( x\^ 
is in hex).
.TP
.BI \-LD\  x
Set the data relocation address to
.I x\^
.RI ( x\^
is in hex).
.TP
.BI \-LC\  x
Set the common relocation address to
.I x\^
.RI ( x\^
is in hex).
.TP
.BI \-LB\  x
Set the bss relocation address to
.I x\^
.RI ( x\^
is in hex).
.TP 
.B  \-d
Force definition of common storage
even if the
.B \-r
flag is present.
.TP 
.B  \-n
Arrange that
when the output file is executed,
the text portion will be read-only and shared
among all users executing the file.
This involves moving the data areas up to the first
possible protection boundary following the
end of the text.
.TP
.BI \-N\  x
Set the data relocation boundary to
.I x\^
for shared text programs.
The value
.I x\^
may be followed by a
.I k\^
or
.I K\^
to indicate multiplication by 1024.
.TP 
.B  \-o
The
.I name\^
argument after
.B \-o
is used as the name of the
.I ld\^
output file, instead of
.BR a.out .
.TP
.B \-e
The following argument is taken to be the
name of the entry point of the loaded
program; location 0 is the default.
.TP
.BI \-F\  x
Add offset
.I x\^
to all data references
.RI ( x\^
is in hex).
.SH EXAMPLE
.IP
ld -s /lib/crt0.o filea.o fileb.o -lc
.PP
will load subroutines "filea" with "fileb" for execution 
and remove its symbol table.
.SH FILES
.ta \w'/usr/lib/lib*.a\ \ \ 'u
/lib/lib*.a	libraries
.br
/usr/lib/lib*.a	more libraries
.br
a.out	default output file
.br
/lib/crt0.o	"C" start up routine
.DT
.SH "SEE ALSO"
ar(1), 
as(1), 
cc(1). 
.\"	@(#)ld.1	5.1 of 11/17/83
